# Players Stats Analysis
The data here are clean and prepared to be use as a input of a [Tableau dashboard](https://public.tableau.com/profile/axel.rasse#!/vizhome/SoccerprojectV2/Dashboard)
We proceed basic task such as handling missing data, converting data type, looking for duplicated values... After a bit of exploration, some new ideas pop up and we have experiment some attributes combinations such as grouping game type in four buckets or creating new features : goals and assists per minutes of every players.

### Summary
1. [Load](#load)
2. [Clean](#clean)
3. [Data Exploration](#explore)
4. [Save](#save)

___
# 1. Load
<a id='load'></a>

In [1]:
import pandas as pd
import numpy as np
players_stats = pd.read_csv('../data/players_database.csv', parse_dates=True)
top_scorer = pd.read_json('../data/250_best_scorer.json')

* **best_scorer.csv** rank the top 250 scorers 

* **players_stat.csv** detailed data of the best 250 scorers _(date, minutes played, goals, assists..)_

## a. Top scorer

In [3]:
top_scorer = top_scorer.sort_values(by='goals', ascending=False)
top_scorer

,name,club,age,league,nationality,match_played,goals,assists,total
0,Ciro Immobile,Lazio,30,Italy,Italy,26,27,7,34
3,Robert Lewandowski,Bayern Munich,31,Germany,Poland,23,25,3,28
13,Erling Haaland,Bor. Dortmund,19,Germany,Norway,22,25,8,33
6,Shon Weissman,Wolfsberger AC,24,Austria,Israel,21,22,3,25
1,Odsonne Edouard,Celtic,22,Scotland,France,27,21,12,33
...,...,...,...,...,...,...,...,...,...
147,Luis Alberto,Lazio,27,Italy,Spain,25,4,13,17
231,Miroslav Stevanovic,Servette FC,29,Switzerland,Bosnia-Herzegovina,21,4,11,15
243,Dan Nistor,CS U Craiova,31,Romania,Romania,22,4,11,15
119,Christopher Nkunku,RB Leipzig,22,Germany,France,23,4,14,18
244,Ruud Vormer,Club Brugge,31,Belgium,Netherlands,27,1,14,15

In [176]:
top_scorer.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 250 entries, 0 to 183
Data columns (total 9 columns):
name            250 non-null object
club            250 non-null object
age             250 non-null int64
league          250 non-null object
nationality     250 non-null object
match_played    250 non-null int64
goals           250 non-null int64
assists         250 non-null int64
total           250 non-null int64
dtypes: int64(5), object(4)
memory usage: 19.5+ KB

## b. Players Stats

In [7]:
players_stats[:5]

,date,comp,round,opponent,minutes,goals,assists,shots_total,shots_on_target,crosses,fouled,pens_made,pens_att,xg,npxg,xa,name
0,2019-08-25,Serie A,Matchweek 1,Sampdoria,90.0,2,0.0,5.0,4.0,0.0,3.0,0,0,1.3,1.3,0.1,Ciro Immobile
1,2019-09-01,Serie A,Matchweek 2,Roma,90.0,0,1.0,7.0,1.0,0.0,1.0,0,0,0.6,0.6,0.7,Ciro Immobile
2,2019-09-08,Euro Qualifying,Group stage,Finland,76.0,1,0.0,5.0,2.0,0.0,0.0,0,0,0.5,0.5,0.1,Ciro Immobile
3,2019-09-15,Serie A,Matchweek 3,SPAL,90.0,1,0.0,0.0,0.0,1.0,0.0,1,1,0.8,0.0,0.1,Ciro Immobile
4,2019-09-22,Serie A,Matchweek 4,Parma,63.0,1,0.0,3.0,2.0,2.0,0.0,0,0,0.2,0.2,0.2,Ciro Immobile

___
# 2. Clean
<a id='clean'></a>

In [178]:
players_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4941 entries, 0 to 4940
Data columns (total 17 columns):
date               4941 non-null object
comp               3610 non-null object
round              4941 non-null object
opponent           4941 non-null object
minutes            4931 non-null float64
goals              4941 non-null int64
assists            4854 non-null float64
shots_total        3873 non-null float64
shots_on_target    3873 non-null float64
crosses            3873 non-null float64
fouled             3873 non-null float64
pens_made          4941 non-null int64
pens_att           4941 non-null int64
xg                 1860 non-null float64
npxg               1860 non-null float64
xa                 1860 non-null float64
name               4941 non-null object
dtypes: float64(9), int64(3), object(5)
memory usage: 656.4+ KB

↳ We might have a lot of missing values, especially in the expect fields (xg, npxg, xa). Maybe player from little league do not have this kind of technology 🤔 

Some of the columns are in the wrong type - for instance, assists, need to be in integer

## a. Missing Values

In [179]:
players_stats['xg'].isnull().value_counts()

True     3081
False    1860
Name: xg, dtype: int64

In [180]:
players_stats[players_stats['xg'].isnull()][-3:]

,date,comp,round,opponent,minutes,goals,assists,shots_total,shots_on_target,crosses,fouled,pens_made,pens_att,xg,npxg,xa,name
4937,2020-02-12,First Division A,Regular Season,Standard Liège,90.0,0,0.0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Ruud Vormer
4938,2020-02-15,First Division A,Regular Season,Waasland-Bev,90.0,0,0.0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Ruud Vormer
4940,2020-02-23,First Division A,Regular Season,Charleroi,90.0,0,0.0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Ruud Vormer

↳ Leave the NaN values like that for the moments

In [181]:
players_stats['assists'].isnull().value_counts()

False    4854
True       87
Name: assists, dtype: int64

In [182]:
players_stats[players_stats['assists'].isnull()]

,date,comp,round,opponent,minutes,goals,assists,shots_total,shots_on_target,crosses,fouled,pens_made,pens_att,xg,npxg,xa,name
2470,2019-07-19,NaN,Regular Season,Voždovac,76.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Nenad Lukic
2471,2019-07-27,NaN,Regular Season,Mladost Lučani,73.0,1,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,Nenad Lukic
2472,2019-08-04,NaN,Regular Season,Spartak Subotic,45.0,1,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,Nenad Lukic
2473,2019-08-10,NaN,Regular Season,Čukarički,67.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Nenad Lukic
2474,2019-08-18,NaN,Regular Season,Vojvodina,90.0,2,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Nenad Lukic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4501,2020-02-08,NB I,Matchweek 20,Paks,90.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Ádám Gyurcsó
4502,2020-02-15,NB I,Matchweek 21,Kisvárda,90.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Ádám Gyurcsó
4503,2020-02-22,NB I,Matchweek 22,Honvéd,90.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Ádám Gyurcsó
4504,2020-02-29,NB I,Matchweek 23,Újpest,45.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Ádám Gyurcsó
4505,2020-03-07,NB I,Matchweek 24,Vidi,90.0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Ádám Gyurcsó

In [183]:
players_stats['minutes'].isnull().value_counts()

False    4931
True       10
Name: minutes, dtype: int64

In [184]:
players_stats[players_stats['minutes'].isnull()]

,date,comp,round,opponent,minutes,goals,assists,shots_total,shots_on_target,crosses,fouled,pens_made,pens_att,xg,npxg,xa,name
635,2019-09-22,Super League,Matchweek 4,Panathinaikos,NaN,0,0.0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Youssef El Arabi
644,2019-11-23,Super League,Matchweek 11,Panionios,NaN,0,0.0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Youssef El Arabi
769,2019-12-21,Premier League,Matchweek 18,Leicester City,NaN,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,Sergio Agüero
821,2019-11-30,NaN,Matchweek 13,Ankaragücü,NaN,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN,NaN,Papiss Demba Cissé
1702,2019-12-15,Premiership,Regular Season,Motherwell,NaN,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN,NaN,Jermain Defoe
3268,2020-01-29,EFL Cup,Semi-finals,Manchester Utd,NaN,0,0.0,0.0,0.0,0.0,1.0,0,0,NaN,NaN,NaN,Gabriel Jesus
3661,2019-12-21,Ligue 1,Matchweek 19,Lille,NaN,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,Islam Slimani
3934,2019-11-06,Champions Lg,Group stage,Shakhtar,NaN,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,Damian Kadzior
4054,2019-11-06,Champions Lg,Group stage,Olympiacos,NaN,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,Philippe Coutinho
4731,2019-08-22,Europa Lg,Play-off Round,Qarabağ Ağdam,NaN,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN,NaN,Kirk Millar

**We have made the choice to convert:**
* Games stats → integer 
* date → datetime

For the moment we have left the excepted missing stats (xg, npxg,xa)

In [185]:
int_column = players_stats.columns[4:13]
players_stats[int_column] = players_stats[int_column].fillna(0)
players_stats[int_column] = players_stats[int_column].astype('int64')

In [186]:
players_stats['date'] = pd.to_datetime(players_stats['date'])

In [187]:
players_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4941 entries, 0 to 4940
Data columns (total 17 columns):
date               4941 non-null datetime64[ns]
comp               3610 non-null object
round              4941 non-null object
opponent           4941 non-null object
minutes            4941 non-null int64
goals              4941 non-null int64
assists            4941 non-null int64
shots_total        4941 non-null int64
shots_on_target    4941 non-null int64
crosses            4941 non-null int64
fouled             4941 non-null int64
pens_made          4941 non-null int64
pens_att           4941 non-null int64
xg                 1860 non-null float64
npxg               1860 non-null float64
xa                 1860 non-null float64
name               4941 non-null object
dtypes: datetime64[ns](1), float64(3), int64(9), object(4)
memory usage: 656.4+ KB

### Handle the missing values in Competition columns

In [188]:
players_stats[['round','comp']].isnull().sum()

round       0
comp     1331
dtype: int64

In [189]:
players_stats[players_stats['comp'].isnull()][-50:]

,date,comp,round,opponent,minutes,goals,assists,shots_total,shots_on_target,crosses,fouled,pens_made,pens_att,xg,npxg,xa,name
4532,2020-02-22,NaN,Regular Season,Oostende,90,0,1,0,0,0,0,0,0,NaN,NaN,NaN,Cyle Larin
4533,2020-02-29,NaN,Regular Season,Kortrijk,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cyle Larin
4534,2020-03-07,NaN,Regular Season,Anderlecht,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Cyle Larin
4733,2019-07-09,NaN,First qualifying round,Hajduk Split,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Hamed Koné
4734,2019-07-18,NaN,First qualifying round,Hajduk Split,90,2,0,0,0,0,0,0,0,NaN,NaN,NaN,Hamed Koné
4735,2019-07-25,NaN,Second qualifying round,Ventspils,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Hamed Koné
4736,2019-08-01,NaN,Second qualifying round,Ventspils,90,0,1,0,0,0,0,0,0,NaN,NaN,NaN,Hamed Koné
4801,2019-08-16,NaN,Regular Season,Chindia,28,1,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4802,2019-08-26,NaN,Regular Season,Hermannstadt,90,1,2,0,0,0,0,1,1,NaN,NaN,NaN,Dan Nistor
4803,2019-09-02,NaN,Regular Season,Sepsi,90,0,1,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4804,2019-09-14,NaN,Regular Season,Botoșani,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4805,2019-09-21,NaN,Regular Season,Astra Giurgiu,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4806,2019-09-27,NaN,Regular Season,Voluntari,90,0,2,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4807,2019-10-05,NaN,Regular Season,FCSB,90,0,1,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4808,2019-10-18,NaN,Regular Season,Gaz Metan,90,0,1,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4809,2019-10-27,NaN,Regular Season,Viitorul,90,0,1,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4810,2019-11-04,NaN,Regular Season,U Craiova,90,1,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4811,2019-11-10,NaN,Regular Season,CFR Cluj,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4812,2019-11-24,NaN,Regular Season,Clinceni,90,0,1,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4813,2019-11-29,NaN,Regular Season,Poli Iași,90,0,1,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4814,2019-12-04,NaN,Regular Season,Chindia,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4815,2019-12-07,NaN,Regular Season,Hermannstadt,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4816,2019-12-13,NaN,Regular Season,Sepsi,72,1,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4817,2020-01-31,NaN,Regular Season,Gaz Metan,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4818,2020-02-09,NaN,Regular Season,Viitorul,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4819,2020-02-15,NaN,Regular Season,Poli Iași,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4820,2020-02-23,NaN,Regular Season,CFR Cluj,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4821,2020-03-01,NaN,Championship round,Gaz Metan,88,0,1,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4822,2020-03-08,NaN,Championship round,FCSB,90,0,0,0,0,0,0,0,0,NaN,NaN,NaN,Dan Nistor
4823,2019-07-21,NaN,Matchweek 1,Young Boys,90,0,0,1,0,2,1,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4824,2019-07-27,NaN,Matchweek 2,Sion,90,0,0,0,0,4,0,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4825,2019-08-04,NaN,Matchweek 3,Luzern,90,1,0,3,1,7,0,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4826,2019-08-10,NaN,Matchweek 4,Basel,90,0,0,1,0,7,2,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4827,2019-08-25,NaN,Matchweek 5,Thun,90,1,1,1,1,7,2,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4828,2019-08-31,NaN,Matchweek 6,Xamax,90,0,0,0,0,5,1,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4829,2019-09-21,NaN,Matchweek 7,St. Gallen,90,0,1,2,0,8,1,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4830,2019-09-26,NaN,Matchweek 8,Lugano,90,0,0,1,0,9,0,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4831,2019-09-29,NaN,Matchweek 9,Zürich,36,0,0,0,0,2,1,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4832,2019-10-26,NaN,Matchweek 12,Sion,90,0,0,1,0,3,3,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4833,2019-11-03,NaN,Matchweek 13,Young Boys,90,0,0,3,0,4,1,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4834,2019-11-09,NaN,Matchweek 14,Luzern,90,0,0,1,0,3,1,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4835,2019-11-23,NaN,Matchweek 15,Basel,90,1,0,6,4,4,2,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4836,2019-12-01,NaN,Matchweek 16,Lugano,90,0,0,3,0,3,4,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4837,2019-12-08,NaN,Matchweek 17,Zürich,90,0,1,1,0,10,0,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4838,2019-12-14,NaN,Matchweek 18,Thun,90,0,0,2,0,5,2,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4839,2020-01-25,NaN,Matchweek 19,Xamax,90,0,0,0,0,7,1,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4840,2020-02-02,NaN,Matchweek 20,Thun,90,0,1,1,1,8,0,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4841,2020-02-09,NaN,Matchweek 21,St. Gallen,90,0,0,1,1,4,0,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4842,2020-02-16,NaN,Matchweek 22,Zürich,90,0,3,1,1,7,2,0,0,NaN,NaN,NaN,Miroslav Stevanovic
4843,2020-02-23,NaN,Matchweek 23,Basel,90,1,0,3,1,7,0,0,0,NaN,NaN,NaN,Miroslav Stevanovic

🤔 The nan value in the Competion columns seems to be the pre saison games and also few asian matchweek game. I decided to drop this rows

players_stats.shape

In [191]:
players_stats.dropna(subset=['comp'], inplace=True)

In [192]:
players_stats.shape

(3610, 17)

## b. No Duplicated Values

In [193]:
players_stats.duplicated(['date','name']).value_counts()

False    3610
dtype: int64

---
# 3. Data exploration
<a id='explore'></a>

In [194]:
sum_stats = players_stats.groupby('name', sort=False).sum()
sum_stats.sort_values(by=['goals'],ascending=False)

,minutes,goals,assists,shots_total,shots_on_target,crosses,fouled,pens_made,pens_att,xg,npxg,xa
name,,,,,,,,,,,,
Robert Lewandowski,2874,39,5,156,77,17,42,4,4,28.9,25.9,6.8
Erling Haaland,2006,36,6,94,51,13,24,3,3,11.2,9.6,0.9
Ciro Immobile,2696,30,7,113,43,12,36,11,13,19.5,10.9,5.3
Kylian Mbappé,2453,30,13,129,73,62,35,0,0,21.8,21.8,11.2
Timo Werner,2742,27,10,117,54,91,31,5,5,21.1,17.3,6.9
...,...,...,...,...,...,...,...,...,...,...,...,...
Andrew Waterworth,335,3,0,0,0,0,0,2,2,0.0,0.0,0.0
Kirk Millar,278,2,1,0,0,0,0,0,0,0.0,0.0,0.0
Ruud Vormer,3040,2,17,3,0,30,4,0,0,0.0,0.0,1.3
Yonatan Cohen,279,1,2,0,0,0,0,0,0,0.0,0.0,0.0
Mersudin Ahmetovic,217,0,0,0,0,0,0,0,0,0.0,0.0,0.0

🤔 weird some players have only one goals and 2 assists. Try to compare it with the top scorrer values:

In [195]:
join = top_scorer.join(sum_stats, on='name', how='inner', rsuffix='_total')
join.reset_index(drop=True, inplace=True)
join[['name','goals','goals_total']][:10]

                 name  goals  goals_total
0       Ciro Immobile     27           30
1  Robert Lewandowski     25           39
2      Erling Haaland     25           36
3         Timo Werner     21           27
4   Cristiano Ronaldo     21           25
5     Odsonne Edouard     20           27
6       Shon Weissman     20           24
7   Alexander Sörloth     19           21
8        Lionel Messi     18           24
9   Jean-Pierre Nsame     18           20

**Hypothesis: maybe one of the two count national and Champions league as well**

## Attribute Combinations
Create a new column by :
        - Game type 
        - minutes per goal
        - minutes per assit

In [196]:
players_stats['game_type'] =  ''
players_stats.loc[players_stats['round'].str.contains('Matchweek'),'game_type'] = 'Domestic league'
players_stats.loc[players_stats['round'].str.contains('Regular Season'),'game_type'] = 'Domestic league'
players_stats.loc[players_stats['comp']=='Champions Lg','game_type'] = 'Champions league'
players_stats.loc[players_stats['comp']=='Europa Lg','game_type'] = 'Europa league'
players_stats['game_type'].replace('','Cup',inplace=True)

In [197]:
stat_without_cup = players_stats[players_stats['game_type'] == 'Domestic league']
regular_stat = stat_without_cup.groupby('name').sum()
regular_stat.sort_values(by=['goals'],ascending=False)

,minutes,goals,assists,shots_total,shots_on_target,crosses,fouled,pens_made,pens_att,xg,npxg,xa
name,,,,,,,,,,,,
Ciro Immobile,2186,27,7,90,39,9,29,10,11,18.8,10.2,5.3
Erling Haaland,1497,25,5,72,38,10,22,1,1,4.9,4.9,0.4
Robert Lewandowski,2041,25,3,106,48,15,34,3,3,20.8,18.6,5.2
Shon Weissman,1814,22,2,78,43,11,23,1,1,0.0,0.0,0.0
Odsonne Edouard,2110,21,9,100,45,2,25,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
Michael Liendl,1948,5,15,52,22,196,29,2,3,0.0,0.0,0.0
Christopher Nkunku,1451,4,12,39,17,96,29,0,0,5.3,5.3,7.8
Luis Alberto,2153,4,12,72,21,114,25,1,1,5.2,4.5,7.7
Andraz Sporar,598,2,0,14,4,1,4,0,0,0.0,0.0,0.0
Ruud Vormer,2374,1,15,0,0,0,0,0,0,0.0,0.0,0.0

In [198]:
join = top_scorer.join(regular_stat, on='name', how='inner', rsuffix='_total')
join.reset_index(drop=True, inplace=True)
join[['name','goals','goals_total']][:10]

                 name  goals  goals_total
0       Ciro Immobile     27           27
1  Robert Lewandowski     25           25
2      Erling Haaland     25           25
3         Timo Werner     21           21
4   Cristiano Ronaldo     21           21
5     Odsonne Edouard     20           21
6       Shon Weissman     20           22
7   Alexander Sörloth     19           19
8        Lionel Messi     18           19
9   Jean-Pierre Nsame     18           18

Goals now corresponds it's work!👍🏼

In [199]:
# add the league_country
players_stats = pd.merge(players_stats, top_scorer[['name','league']], how='left')

In [200]:
# add Minutes per Goals and Minutes per assists
df = players_stats.groupby(['name','date']).sum().groupby('name').cumsum()
min_per_goal = df['minutes'] / df['goals']
min_per_assit = df['minutes'] / df['assists']
min_per_goal = min_per_goal.replace(np.inf,1000).astype('int32')
min_per_assit = min_per_assit.replace(np.inf,1000).astype('int32')

In [201]:
min_per_assit = min_per_assit.rename('min_per_assit')
min_per_goal = min_per_goal.rename('min_per_goal')

In [202]:
players_stats = pd.merge(players_stats, min_per_assit, left_on=['name','date'], right_index=True, how='left')
players_stats = pd.merge(players_stats, min_per_goal, left_on=['name','date'], right_index=True, how='left')

In [203]:
# add the players' club
players_stats = pd.merge(players_stats, top_scorer[['name','club']], how='left')

In [204]:
# add a column for each week of the month
week_of_month = players_stats.set_index(['date','name'],drop=False)
week_of_month =(week_of_month['date'].dt.day-1) // 7 + 1
week_of_month.rename('Week_of_month')[:5]

date        name
2019-08-25  Ciro Immobile    4
2019-09-01  Ciro Immobile    1
2019-09-15  Ciro Immobile    3
2019-09-22  Ciro Immobile    4
2019-09-25  Ciro Immobile    4
Name: Week_of_month, dtype: int64

In [205]:
players_stats = pd.merge(players_stats, week_of_month,left_on=['date','name'], right_index=True, how='left')

In [206]:
players_stats.rename(columns={
                              'date_x':'date','date_y':'Week_of_month',
                              'min_per_assit_y':'min_per_assit',
                              'min_per_goal_y':'min_per_goal'
                             }
                     ,inplace=True)

---
# 4. Save
<a id='save'></a>

In [207]:
# clean a little bit
players_stats.drop(columns=['round','min_per_goal_x','min_per_assit_x'],inplace=True, errors='ignore')
players_stats[:5]

,date,comp,opponent,minutes,goals,assists,shots_total,shots_on_target,crosses,fouled,...,xg,npxg,xa,name,game_type,league,min_per_assit,min_per_goal,club,Week_of_month
0,2019-08-25,Serie A,Sampdoria,90,2,0,5,4,0,3,...,1.3,1.3,0.1,Ciro Immobile,Domestic league,Italy,90,45,Lazio,4
1,2019-09-01,Serie A,Roma,90,0,1,7,1,0,1,...,0.6,0.6,0.7,Ciro Immobile,Domestic league,Italy,180,90,Lazio,1
2,2019-09-15,Serie A,SPAL,90,1,0,0,0,1,0,...,0.8,0.0,0.1,Ciro Immobile,Domestic league,Italy,270,90,Lazio,3
3,2019-09-22,Serie A,Parma,63,1,0,3,2,2,0,...,0.2,0.2,0.2,Ciro Immobile,Domestic league,Italy,333,83,Lazio,4
4,2019-09-25,Serie A,Inter,37,0,0,1,0,0,0,...,0.1,0.1,0.0,Ciro Immobile,Domestic league,Italy,370,92,Lazio,4

In [208]:
# players_stats.to_csv('../database.csv')

**➤ save to a google spreadsheet**

In [209]:
import gspread
from df2gspread import df2gspread as d2g
from oauth2client.service_account import ServiceAccountCredentials

In [210]:
scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_name(
    'drive_key.json', scope)
gc = gspread.authorize(credentials)

In [211]:
spreadsheet_key = '10EDLlCx53daOsInMuCSSxqTvVz4O1z7ijj6WcO3PW8Q'
wks_name = 'Master'
d2g.upload(players_stats, spreadsheet_key, wks_name, credentials=credentials, row_names=True)